### ISSUE TITLE
Leading closing html comment in page content

### ISSUE THREAD

**Issue by willsmith9182** [kovetskiy/mark#42] opened 2020-12-02 17:56 UTC
Howdy, 

am i missing something? from what i see all are opened and closed correctly but i get a leading `-->` on pages in confluence

.md file:
```
<!-- Space: DD -->
<!-- Parent: On-boarding docs -->
<!-- Parent: Systems Development -->
<!-- Parent: Application -->
<!-- Parent: BuildTools -->
<!-- Title: Repositories using BuildTools -->

<!-- Macro: :autogen:
     Template: ac:status
     Title: AUTOMATED
     Color: Yellow -->

:autogen:
this document is generated, do not edit manually.

----

some other content (no html comments at all in this section)

```

Expected: 
no leading `-->` in content

Actual:
leading `-->` in content of page, can bee see in raw macroRenderedOutput in trace request as `<p>&ndash;&gt;</p>\n\n`

![image](https://user-images.githubusercontent.com/11752440/100912062-ee88a180-34c7-11eb-8c8c-a525bb5181c1.png)

**Comment by kovetskiy** [comment] 2020-12-03 21:33
Hi, I was not able to reproduce this on 3.5.

**Comment by willsmith9182** [comment] 2020-12-06 22:50
I deleted and re-created my page, it's still there using 3.5 too. 

I can see in a trace log there's a `-->` but i can't figure out where it's come from 👍 
```
2020-12-06 22:49:09 [TRACE]: rendering markdown:
                             -->

                             <ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">Yellow</ac:parameter><ac:parameter ac:name="title">AUTOMATED</ac:parameter><ac:parameter ac:name="subtle">false</ac:parameter></ac:structured-macro>
                             this document is generated, do not edit manually.

                             ----

                             ## Build Tools Type: Cake
```

**Comment by willsmith9182** [comment] 2020-12-06 22:58
I narrowed it down, removing the following directives removed the trailing `-->`

```<!-- Parent: On-boarding docs -->
<!-- Parent: Systems Development -->
<!-- Parent: Application -->
<!-- Parent: BuildTools -->```

i wdoner if it's spaces in the parents or just multiples that causes it?

**Comment by bencurrandev** [comment] 2021-03-10 05:26
I am getting the same issue, the length of the closing html comment differs based on how many parent tags are present. I do also have spaces in the parent names, but there is no correlation between the spaces and tailing characters. They still appear if I remove all spaces from the parents. Exact same as @willsmith9182 in the trace as well. Happened in 4.2 and 5.2.1.

**Comment by johns10** [comment] 2021-06-18 17:29
I am also getting the same issue with this header:

```
<!-- Space: TD -->
<!-- Title: Equipment BOM Groups Menu -->
<!-- Attachment: images/equipment_bom_groups_maintenance_settings_section.png -->
<!-- Attachment: images/equipment_bom_groups_form_reference.png -->
<!-- Attachment: images/equipment_bom_groups_menu_reference.png -->
```

**Comment by johns10** [comment] 2021-06-18 17:32
I'm not sure it's related to spaces though.  I retried with this header, and I still get it:

```
<!-- Space: TD -->
<!-- Title: equipmentbomgroupsmenu -->
<!-- Attachment: images/equipment_bom_groups_maintenance_settings_section.png -->
<!-- Attachment: images/equipment_bom_groups_form_reference.png -->
<!-- Attachment: images/equipment_bom_groups_menu_reference.png -->
```

Also worth noting, if I remove the last ->, it adds a trailing ng (last two letters of last filename).

**Comment by johns10** [comment] 2021-07-07 17:25
I pulled down the repo so I could repro locally and characterize.  I made 2 test files, one with only the necessary front matter, and another that duplicated the attachment in the front matter multiple times.

![1](https://user-images.githubusercontent.com/3057629/124802770-530c5300-df26-11eb-9783-1165abbd077e.png)
[test1.md](https://github.com/kovetskiy/mark/files/6778994/test1.md)
[test2.md](https://github.com/kovetskiy/mark/files/6778995/test2.md)

test1.md results:
```>

# Test File```

test2.md results:
```tachment: images/1.png -->

# Test File```

It's not 1:1 for lines of front matter to characters left in the markdown, but it's close.

I instrumented by inserting `fmt.Printf("MD: %s", markdown)` into main.go at line 165.

**Comment by johns10** [comment] 2021-07-07 17:29
My working theory is that this is an issue with the offset calculation in `meta.go`

**Comment by johns10** [comment] 2021-07-07 17:33
I have an anemic fix that works on my local:

`offset += len(line) + 2`

@kovetskiy can you validate this doesn't break other things?

**Comment by johns10** [comment] 2021-07-07 17:34
Also, can we change the name of the ticket to:

`Mark includes the last N characters of frontmatter, where N is proportional to the number of lines of frontmatter in the file`

**Comment by johns10** [comment] 2021-07-07 17:48
@kovetskiy ,

I made a PR for this. It's my first one so be gentle!!

**Comment by johns10** [comment] 2021-07-14 14:03
@willsmith9182 our line endings are \r\n. if we fix the line endings to just \n, it should resolve this.

**Comment by Dosenwerfer** [comment] 2021-11-03 14:56
I can confirm that this happens when using Windows line endings \r\n. Unix line endings \n fix this issue.

**Comment by kovetskiy** [comment] 2021-11-03 15:14
This can be fixed programmatically, I just didn't think \r\n is still a
thing. Mark could replace \r\b with \n after reading the contents of the
file.

**Comment by Dosenwerfer** [comment] 2021-11-06 23:14
Yes, unfortunately it is very much still a thing. It would be nice if that
replacement could be done by Mark.

**Closed** 2021-11-08 14:16 UTC
Labels: bug
