### ISSUE TITLE
Question & No meta data Panic 

### ISSUE THREAD

**Issue by joyfulrabbit** [kovetskiy/mark#233] opened 2022-12-12 19:52 UTC
The format of your URL matters if you don't have meta data in your headers. This exact formatting is not clearly documented and I'd like more examples of this. I'm running Confluence 7.13.7 hosted on prem. I'm not sure if I'm using the wrong url format, but when I use this following format (and confirm the page works before deploying) with no meta data, mark crashes.

This URL format with no meta-data :
<confluence-url>/pages/viewpage.action?pageId=<pageId>

a command like this:
`./mark -c ~/.config/mark/wiki-dev.cfg -l "https://<base_urL>/pages/viewpage.action?pageId=122781799" -f ~/test/my_doc.md --dry-run`

or this

`./mark -c ~/.config/mark/wiki-dev.cfg -l "<base_url>/pages/viewpage.action?pageId=122781799" -f ~/test/my_doc.md ----trace --debug`

Throws this this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100b5ecf4]

goroutine 1 [running]:
main.processFile({0x1400001c780, 0x48}, 0x1008860f8?, {{0x16f5af560, 0x2d}, 0x0, 0x0, 0x0, 0x1, 0x1, ...}, ...)
        github.com/kovetskiy/mark/main.go:208 +0x1f4
main.main()
        github.com/kovetskiy/mark/main.go:159 +0x51
```

**Comment by joyfulrabbit** [comment] 2022-12-12 19:56
I get the same output if I use:
"<source_url>/pages/editpage.action?pageId=122781799"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x10234ecf4]

goroutine 1 [running]:
main.processFile({0x16ddbf4c3, 0x1d}, 0x1020760f8?, {{0x16ddbf4c3, 0x1d}, 0x0, 0x0, 0x0, 0x0, 0x1, ...}, ...)
        github.com/kovetskiy/mark/main.go:208 +0x1f4
main.main()
        github.com/kovetskiy/mark/main.go:159 +0x510

**Comment by mrueg** [comment] 2023-08-09 12:21
Duplicate of https://github.com/kovetskiy/mark/issues/228

Please try again with a later version of mark and report back if the issue still exists.

**Closed by mrueg** 2023-08-09 12:21 UTC
